version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y jq

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 988253048728.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - IMAGE_TAG=$(jq -r ".version" package.json)
      - npm run docker

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 988253048728.dkr.ecr.us-east-1.amazonaws.com/mainserver:$IMAGE_TAG
